data:
    train: train.xyz
    valid: valid.xyz

loss:
    - +PerAtomEnergyLoss()
    - +ForceRMSE()

fitting:
    trainer_kwargs:
        max_epochs: 20
        accelerator: cpu

    optimizer:
        name: Adam
        lr: 0.0001

    auto_fit_reference_energies: true

wandb: null
general:
    progress: logged
    run_id: mp0-fine-tune
