CUTOFF: 3.7

general:
    progress: logged

model:
    +load_model:
        path: graph-pes-results/train-nequip/model.pt
        # you would need to change ^this path if you wanted to
        # fine-tune a different model

data:
    train:
        +file_dataset:
            path: train-cgap20u.xyz
            cutoff: =/CUTOFF
            n: 1280
            shuffle: false
    valid:
        +file_dataset:
            path: val-cgap20u.xyz
            cutoff: =/CUTOFF
    test:
        +file_dataset:
            path: test-cgap20u.xyz
            cutoff: =/CUTOFF

loss:
    - +PerAtomEnergyLoss()
    - +ForceRMSE()

fitting:
    # important config option to automatically align the model's
    # energy predictions to the new dataset
    auto_fit_reference_energies: true

    trainer_kwargs:
        max_epochs: 25
        accelerator: auto

    optimizer:
        +Optimizer:
            name: AdamW
            lr: 0.0001

    loader_kwargs:
        batch_size: 16

wandb:
    project: graph-pes-quickstart
