CUTOFF: 3.7

general:
    progress: logged

# finetune a pre-trained NequIP model ...
model:
    +load_model:
        path: # insert path to model when using this script

# ... on structures from local files ...
data:
    train:
        +file_dataset:
            path: train-cgap20u.xyz
            cutoff: =/CUTOFF
            n: 1280
            shuffle: false
    valid:
        +file_dataset:
            path: val-cgap20u.xyz
            cutoff: =/CUTOFF
    test:
        +file_dataset:
            path: test-cgap20u.xyz
            cutoff: =/CUTOFF

# ... on both energy and forces ...
loss:
    - +PerAtomEnergyLoss()
    - +ForceRMSE()

# ... with the following settings ...
fitting:
    # important config option to automatically align the model's
    # energy predictions to the new dataset
    auto_fit_reference_energies: true

    trainer_kwargs:
        max_epochs: 25
        accelerator: auto

    optimizer:
        +Optimizer:
            name: AdamW
            lr: 0.0001

    loader_kwargs:
        batch_size: 16

# ... and log to Weights & Biases
wandb:
    project: graph-pes-quickstart
