general:
  run_id: quickstart-run
  progress: logged

# train a PaiNN model ...
model:
  graph_pes.models.PaiNN: # or NequIP, MACE, TensorNet etc.
    layers: 3
    cutoff: 3.0 # radial cutoff in Å

# ... on structures from the QM7 dataset ...
data:
  graph_pes.data.load_atoms_dataset:
    id: QM7
    cutoff: 3.0 # radial cutoff in Å
    n_train: 1_000
    n_valid: 100

# ... using a simple energy loss function ...
loss: graph_pes.training.loss.PerAtomEnergyLoss()

# ... with the following settings ...
fitting:
  trainer_kwargs: # passed straight to the lightning trainer
    max_epochs: 25
    accelerator: auto # use a gpu if available

  optimizer:
    graph_pes.training.opt.Optimizer:
      name: AdamW
      lr: 0.01

  loader_kwargs: # passed straight to the data loader
    batch_size: 16

# ... and log to Weights & Biases
wandb:
  project: graph-pes
