general:
  run_id: quickstart-run
  progress: logged

# train a PaiNN model ...
model:
  graph_pes.models.PaiNN: # or NequIP, MACE, TensorNet etc.
    layers: 3
    cutoff: 3.0 # radial cutoff in Å

# ... on structures from local files ...
data:
  train:
    graph_pes.data.file_dataset:
      path: train.xyz
      cutoff: 3.0 
      n: 1000
      shuffle: false
  valid:
    graph_pes.data.file_dataset:
      path: val.xyz
      cutoff: 3.0 
 
# ... using a simple energy loss function ...
loss: graph_pes.training.loss.PerAtomEnergyLoss()

# ... with the following settings ...
fitting:
  trainer_kwargs:
    max_epochs: 200
    accelerator: auto

  optimizer:
    graph_pes.training.opt.Optimizer:
      name: AdamW
      lr: 0.0001

  loader_kwargs:
    batch_size: 16

# ... and log to Weights & Biases
wandb:
  project: graph-pes-demo
