# train a SchNet model...
model:
    +SchNet:
        layers: 3
        channels: 64

# ...using some of the QM7 structures...
data:
    +load_atoms_dataset:
        id: QM7
        cutoff: 5.0
        n_train: 5_000
        n_valid: 100

# ...training on energy labels
loss: +PerAtomEnergyLoss()