general:
    seed: 42
    run_id: mace-c-gap-20u

misc:
    CUTOFF: 3.7

model:
    offset: +LearnableOffset()
    core-repulsion:
        +ZBLCoreRepulsion:
            trainable: true
            cutoff: "!~/misc/CUTOFF"
    many-body:
        +MACE:
            elements: [C]
            cutoff: "!~/misc/CUTOFF"
            channels: 128
            hidden_irreps: 0e + 1o
            self_connection: true

data:
    +load_atoms_dataset:
        id: C-GAP-20U
        cutoff: "!~/misc/CUTOFF"
        n_train: 5000
        n_valid: -1
        split: random

loss:
    - +PerAtomEnergyLoss()
    - +WeightedLoss:
          component:
              +PropertyLoss: { property: forces, metric: RMSE }
          weight: 3.0

fitting:
    trainer_kwargs:
        max_epochs: 1000
        accelerator: gpu

    callbacks:
        - +graph_pes.training.callbacks.DumpModel:
              every_n_val_checks: 10

    early_stopping_patience: 50

    optimizer:
        +Optimizer:
            name: AdamW
            lr: 0.003

    scheduler:
        +LRScheduler:
            name: ReduceLROnPlateau
            patience: 10
            factor: 0.8

    loader_kwargs:
        batch_size: 32
        num_workers: 4
