CUTOFF: 3.7

general:
    seed: 42
    run_id: mace-c-gap-20u

model:
    offset: +LearnableOffset()
    core-repulsion:
        +ZBLCoreRepulsion:
            trainable: true
            cutoff: =/CUTOFF
    many-body:
        +MACE:
            elements: [C]
            cutoff: =/CUTOFF
            channels: 128
            hidden_irreps: 0e + 1o
            self_connection: true

data:
    train:
        path: data/train.xyz
        n: 5000
    valid: data/valid.xyz
    test:
        bulk: data/bulk-test.xyz
        slab: data/slab-test.xyz

loss:
    energy: +PerAtomEnergyLoss()
    forces:
        +ForceRMSE:
            weight: 10.0

fitting:
    trainer_kwargs:
        max_epochs: 1000
        accelerator: gpu

    callbacks:
        - +graph_pes.training.callbacks.DumpModel:
              every_n_val_checks: 10

    early_stopping:
        patience: 50

    optimizer:
        name: AdamW
        lr: 0.003

    scheduler:
        name: ReduceLROnPlateau
        patience: 10
        factor: 0.8

    loader_kwargs:
        batch_size: 32
        num_workers: 4
