name: CI

on:
  pull_request:

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for CHANGELOG.md changes
        run: |
          git fetch origin ${{ github.base_ref }}
          if ! git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q "CHANGELOG.md"; then
            echo "Error: No changes to CHANGELOG.md found in this pull request"
            exit 1
          fi

  

  find_todos:
    runs-on: ubuntu-latest
    on:
      pull_request_review_comment:
        types: [edited, deleted]
      pull_request:

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Todos
        uses: phntmxyz/pr_todo_checker@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}