name: Source Code Tests
on: [push]
permissions:
    contents: read
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                  cache: pip
                  cache-dependency-path: pyproject.toml
                  python-version: 3.9
            - name: update pip
              run: pip install --upgrade pip
            - name: Install graph-pes
              run: pip install -e ".[test]"
            - name: Run tests
              run: pytest --cov src --cov-report xml
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
