name: CI

on: [push]

permissions:
  contents: read

jobs:
  # docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: 3.8
  #     - name: Install requirements
  #       run: pip install -r docs/requirements.txt
  #     - name: Install pandoc
  #       run: sudo apt-get install -y --no-install-recommends pandoc
  #     - name: Build docs
  #       # -n: nitpick
  #       # -W: turn warnings into errors
  #       run: sphinx-build -nW docs/source docs/build --keep-going

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: update pip
        run: pip install --upgrade pip
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        run: ruff check

  tests:
    needs: style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
          # TODO: re-enable these once go public: otherwise expensive
          # - 3.9
          # - "3.10"
          # - 3.11
    name: test - ${{ matrix.python-version }}
    steps:
      ### SETUP ###
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        # Caching the python environment. This is different to just caching the
        # pip wheels, as we save on the installation time of large packages such
        # as torch.
        uses: actions/cache@v4.0.2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('**/pyproject.toml') }}
      - name: Install graph-pes and required dependencies
        # Install graph-pes and update any dependencies that are not up to date in
        # the cached environment. We use the --upgrade-strategy eager flag to get
        # the latest version of the dependencies.
        run: pip install --upgrade --upgrade-strategy eager ".[test,docs]"
      - name: Useful info
        run: pip freeze
      ### CODE TESTS ###
      - name: Run pyright
        run: pyright
      - name: Run tests
        run: pytest --cov --cov-report xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        # only upload coverage reports for the first python version
        if: matrix.python-version == '3.8'
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      ### DOCS ###
      - name: Install pandoc
        run: sudo apt-get install -y --no-install-recommends pandoc
      - name: Build docs
        # -n: nitpick
        # -W: turn warnings into errors
        run: sphinx-build -nW docs/source docs/build --keep-going
