name: Source Code Tests

on: [push]

permissions:
  contents: read

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: update pip
        run: pip install --upgrade pip
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        run: ruff check

  tests:
    needs: style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
          # TODO: re-enable these once go public: otherwise expensive
          # temp comment
          # - 3.9
          # - "3.10"
          # - 3.11
    name: test - ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        uses: actions/cache@v4.0.2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('**/pyproject.toml') }}
      - name: Install pip dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install ".[test]"
          pip cache purge
      - name: Useful info
        run: pip freeze
      # - name: Run pytest checks
      # - name: update pip
      #   run: pip install --upgrade pip
      # - name: Install graph-pes
      #   run: pip install ".[test]"
      # - name: Install pyright
      #   run: pip install pyright
      # - name: Useful info
      #   run: pip freeze
      - name: Run pyright
        run: pyright --verbose
      - name: Run tests
        run: pytest --cov --cov-report xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        # only upload coverage reports for the first python version
        if: matrix.python-version == '3.8'
        with:
          token: ${{secrets.CODECOV_TOKEN}}
