name: tests

on:
  push:

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.9
          - "3.10"
          - 3.11
    name: test - ${{ matrix.python-version }}
    steps:
      ### SETUP ###
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache dependencies
        # Caching the python environment. This is different to just caching the
        # pip wheels, as we save on the installation time of large packages such
        # as torch.
        uses: actions/cache@v4.0.2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install graph-pes and required dependencies
        # Install graph-pes and update any dependencies that are not up to date in
        # the cached environment. We use the --upgrade-strategy eager flag to get
        # the latest version of the dependencies.
        run: pip install --upgrade --upgrade-strategy eager ".[test,docs]"

      - name: Useful info
        run: pip freeze

      ### CODE TESTS ###
      - name: Run tests
        run: PYTHONPATH=. pytest --cov --cov-report xml tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        # only upload coverage reports for the first python version
        if: matrix.python-version == '3.9'
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Run a very small training run
        run: |
          graph-pes-train configs/minimal.yaml \
              data/+load_atoms_dataset/n_train=10 \
              data/+load_atoms_dataset/n_valid=10 \
              fitting/trainer_kwargs/max_epochs=5 \
              wandb=null \
              general/root_dir=results \
              general/run_id=test-run

      - name: Run a very small testing run
        run: |
          graph-pes-test model_path=results/test-run/model.pt \
              data/+file_dataset/path=tests/helpers/test.xyz \
              data/+file_dataset/cutoff=5.0

  docs:
    runs-on: ubuntu-latest
    steps:
      ### SETUP ###
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install pandoc
        run: sudo apt-get install -y --no-install-recommends pandoc

      - name: Cache dependencies
        # Caching the python environment. This is different to just caching the
        # pip wheels, as we save on the installation time of large packages such
        # as torch.
        uses: actions/cache@v4.0.2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install graph-pes and required dependencies
        # -e flag to install in place, allowing for correct links
        run: pip install -e".[docs]"

      ### DOCS ###
      - name: Build docs
        # -n: nitpick:
        # -W: turn warnings into errors
        run: sphinx-build -nW docs/source docs/build --keep-going

      - name: Publich docs
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true

  mace-torch-interface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache dependencies
        # Caching the python environment. This is different to just caching the
        # pip wheels, as we save on the installation time of large packages such
        # as torch.
        uses: actions/cache@v4.0.2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install graph-pes and required dependencies
        # Install graph-pes and update any dependencies that are not up to date in
        # the cached environment. We use the --upgrade-strategy eager flag to get
        # the latest version of the dependencies.
        run: pip install --upgrade --upgrade-strategy eager ".[test]"

      - name: Install mace-torch
        run: pip install mace-torch

      - name: Run tests
        run: pytest src/graph_pes/interfaces/mace_test.py -vvv --import-mode=importlib
